# Generated by Django 5.0.7 on 2024-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
