# Generated by Django 5.0.7 on 2024-07-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogs_likes_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='fb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='insta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/profile/'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='snap',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
