# Generated by Django 5.0.7 on 2024-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profileuser_fb_profileuser_insta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='fb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='insta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='snap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
